---
title: "janitor in rmd"
author: "greg dubrow"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r pkg load, include = FALSE, ECHO = FALSE}

library(janitor)
library(tidyverse)
library(readxl)
library(knitr)
```


```{r tabyl output, ECHO = FALSE}

# use knitr::kable to render nicer looking table in html
mtcars %>%
  tabyl(gear, cyl) %>%
  adorn_totals("row") %>% # creates row of sum of cols
  adorn_totals("col") %>% # creates col of sum of rows
#  adorn_totals(c("col", "row")) %>% # does both can add in 1 statement or separate
  adorn_percentages(c("col")) %>% # sums columnwise, bottom row should be 100%
  adorn_percentages(c("row")) %>% # sum row-wise to 100% 
         #can only be one or the other, row or col, last one in chain will output
  adorn_pct_formatting(digits = 1) %>% 
  adorn_ns() %>% # if NA is set, will add them to output
  adorn_title("top", row_name = "Gears", col_name = "Cylinders") %>% # adds field titles if output
  kable()
```


```{r pressure, include = FALSE, echo=FALSE}
## Including Plots
#You can also embed plots, for example:
#plot(pressure)

#Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that #generated the plot.
```